iwear/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^stylist/', include('stylist.urls', namespace='stylist')),
    url(r'^admin/', admin.site.urls),
]

stylist/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout

from stylist.views import AddItem, MyForecast, MyItems, \
        RemoveItem, SignUpView


urlpatterns = [
    url(r'^$', login, {'template_name': 'stylist/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': 'stylist:login'}, name='logout'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^my_items/$', login_required(MyItems.as_view()), name='my_items'),
    url(r'^add_item/$', login_required(AddItem.as_view()), name='add_item'),
    url(r'^remove_item/(?P<pk>[0-9]+)/$', login_required(RemoveItem.as_view()),
        name='remove_item'),
    url(r'^forecast/$', login_required(MyForecast.as_view()), name='forecast'),
]

stylist/models.py
from __future__ import unicode_literals

from collections import defaultdict

from django.contrib.auth.models import AbstractUser
from django.db import models

from iwear import settings


class MyUser(AbstractUser):
    city = models.CharField(max_length=256)
    woeid = models.IntegerField()
    zip_code = models.IntegerField()


class Item(models.Model):
    PANTS = 0
    SKIRT = 1
    SHORTS = 2
    SHIRT = 3
    SWEATER = 4
    TEE = 5
    TYPE_CHOICES = (
        (PANTS, 'Pants'),
        (SHORTS, 'Shorts'),
        (SKIRT, 'Skirt'),
        (SHIRT, 'Shirt'),
        (SWEATER, 'Sweater'),
        (TEE, 'Tee'),
    )
    BLACK = 0
    WHITE = 1
    RED = 2
    PINK = 3
    COLOR_CHOICES = (
        (BLACK, 'Black'),
        (WHITE, 'White'),
        (RED, 'Red'),
        (PINK, 'Pink'),
    )
    WARM = 0
    MILD = 1
    COLD = 2
    DIURNAL_VARIATION = 18
    TEMPERATURE_CHOICES = (
        (WARM, 'Warm'),
        (MILD, 'Mild'),
        (COLD, 'Cold'),
    )
    TEMP_WARM_MIN = 68
    TEMP_COLD_MAX = 50

    BOTTOMS = [PANTS, SKIRT, SHORTS]
    TOPS = [SHIRT, TEE]
    OUTERS = [SWEATER]

    COLOR_SET_SCORES = defaultdict(int)
    COLOR_SET_SCORES.update({
            frozenset([BLACK]): 2,
            frozenset([BLACK, PINK]): 3,
            frozenset([BLACK, RED]): 4,
            frozenset([BLACK, WHITE]): 5,
            frozenset([WHITE]): 4,
            frozenset([WHITE, PINK]): 5,
            frozenset([WHITE, RED]): 3,
            frozenset([RED]): 1,
            frozenset([RED, PINK]): 0,
            frozenset([PINK]): 1,
            frozenset([BLACK, WHITE, RED]): 4,
            frozenset([BLACK, WHITE, PINK]): 5,
            frozenset([BLACK, RED, PINK]): 1,
            frozenset([WHITE, RED, PINK]): 0,
    })

    @classmethod
    def classify_temperature(cls, temp):
        """Map temperature to one of TEMPERATURE_CHOICES intervals."""
        if temp >= cls.TEMP_WARM_MIN:
            return cls.WARM
        elif temp <= cls.TEMP_COLD_MAX:
            return cls.COLD
        else:
            return cls.MILD

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    item_type = models.IntegerField(choices=TYPE_CHOICES)
    color = models.IntegerField(choices=COLOR_CHOICES)
    temperature = models.IntegerField(choices=TEMPERATURE_CHOICES,
                                      verbose_name='I wear it when it\'s')

    def __unicode__(self):
        return "%s %s for %s weather" % (self.get_color_display(),
                                         self.get_item_type_display(),
                                         self.get_temperature_display())

stylist/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from stylist.models import MyUser


class MyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = MyUser
        widgets = {'woeid': forms.HiddenInput()}
        fields = ("username", "city", "zip_code", "woeid")

stylist/views.py
import itertools

from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, TemplateView

from stylist.forms import MyUserCreationForm
from stylist.models import Item


class SignUpView(CreateView):
    """Collect user data and retrieve woeid for given zip code."""

    form_class = MyUserCreationForm
    template_name = 'stylist/signup.html'
    success_url = reverse_lazy('stylist:login')


class MyItems(ListView):
    """List items owned by logged user."""

    model = Item
    template_name = 'stylist/my_items.html'

    def get_queryset(self):
        return super(MyItems, self).get_queryset().filter(
                owner=self.request.user)


class AddItem(CreateView):
    """Add item to logged user's wardrobe."""

    model = Item
    success_url = reverse_lazy('stylist:my_items')
    fields = ['item_type', 'color', 'temperature']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AddItem, self).form_valid(form)


class RemoveItem(DeleteView):
    """Remove item from logged user's wardrobe."""

    model = Item
    success_url = reverse_lazy('stylist:my_items')

    def get_queryset(self):
        return super(RemoveItem, self).get_queryset().filter(
                owner=self.request.user)


class MyForecast(TemplateView):
    """Retrieve today's forecast for user's location, display set of clothes
    from user's wardrobe.

    Choose clothes based on availability, temperature and matching colors.
    """

    get_template_name = "stylist/forecast.html"
    post_template_name = "stylist/what_to_wear.html"

    def get_template_names(self):
        return [{'GET': self.get_template_name,
                 'POST': self.post_template_name}[self.request.method]]

    def what_to_wear(self, low, high):
        """Return best scored combination of clothes for given temperatures."""

        high_classification = Item.classify_temperature(high)
        tops = self.request.user.item_set.filter(
                item_type__in=Item.TOPS,
                temperature=high_classification)
        bottoms = self.request.user.item_set.filter(
                item_type__in=Item.BOTTOMS,
                temperature=high_classification)
        outers = []
        if high - low >= Item.DIURNAL_VARIATION or \
                high_classification == Item.COLD:
            outers = self.request.user.item_set.filter(
                    item_type__in=Item.OUTERS,
                    temperature=high_classification)

        def score(top, bottom, outer):
            """Score given set of clothes based on colors."""
            colors = [top.color, bottom.color]
            if outer:
                colors.append(outer.color)
            return Item.COLOR_SET_SCORES[frozenset(colors)]

        combinations = list(itertools.product(tops, bottoms, outers or [None]))
        combinations.sort(lambda x, y: cmp(score(*y), score(*x)))
        return combinations[0] if combinations else ()

    def get_context_data(self, **kwargs):
        context = super(MyForecast, self).get_context_data(**kwargs)
        if self.request.method == 'POST':
            low = int(self.request.POST["low"])
            high = int(self.request.POST["high"])
            context["low"] = low
            context["high"] = high
            high_classification = Item.classify_temperature(high)
            context["sweater_needed"] = \
                high - low >= Item.DIURNAL_VARIATION or \
                high_classification == Item.COLD
            context["clothes"] = self.what_to_wear(low, high)
        else:
            context['woeid'] = self.request.user.woeid
        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

stylist/templates/stylist/base.html
{% load staticfiles %}

<html>
    <head>
        {% block head %}
            <title>iWear</title>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
            <script src="{% static "api_calls.js" %}"></script>
            <script src="{% static "scriptcaller.min.js" %}"></script>
            <link rel="stylesheet" href="{% static "zurb/css/foundation.min.css" %}">
            <script>
                // Setup CSRF token for AJAX requests
                function csrf_safe_method(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                };
                $.ajaxSetup({
                    cache: false,
                    beforeSend: function(xhr, settings) {
                       if (!csrf_safe_method(settings.type)) {
                           xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
                       }
                    }
                });
            </script>
        {% endblock head %}
    </head>
    <body>
        <div class="top-bar">
            <div class="top-bar-left">
                <ul class="menu">
                    <li class="menu-text">iWear</li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'stylist:my_items' %}">My wardrobe</a></li>
                        <li><a href="{% url 'stylist:forecast' %}">Forecast</a></li>
                        <li><a href="{% url 'stylist:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <br>
        {% block content %}
        {% endblock content %}
        <footer>
            <ul class="menu align-right">
                <li class="menu-text"><a href="https://www.yahoo.com/?ilc=401" target="_blank"><img src="https://poweredby.yahoo.com/purple.png" width="134" height="29"/></a></li>
            </ul>
        </footer>
    </body>
</html>

stylist/templates/stylist/forecast.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>What to wear today:</h3>
    <div id="what_to_wear" class="primary callout">
        Loading...
    </div>
</div>
<script>
    function callbackFunction(data, retryFunc) {
        try {
            var results = data.query.results;
            if (results) {
                var temperature = results.channel.item.forecast[0];  // 0 element is today's weather
                if ((temperature.low != undefined) && (temperature.high != undefined)) {
                    $.ajax({
                        method: "POST",
                        data: {
                            low: temperature.low,
                            high: temperature.high
                        }
                    }).done(function(data) {
                        $("#what_to_wear").html(data);
                    });
                } else {
                    retryFunc("Error retrieving weather data!");
                }
            } else {
                retryFunc("Error retrieving weather data!");
            }
        } catch(e) {
            retryFunc("Problem communicating with the server. Try again later.");
        }
    }

    function getForecast() {
        var YQL = "https://query.yahooapis.com/v1/public/yql";
        var url = YQL + "?q=select * from weather.forecast where woeid={{ woeid }};&format=json";
        // Test: url = "/static/test_forecast.js";
        apiCall(url, callbackFunction)
    }

    // OnLoad
    $(function() {
        getForecast();
    });
</script>
{% endblock content %}

stylist/templates/stylist/item_confirm_delete.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>Remove item</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>
{% endblock content %}

stylist/templates/stylist/item_form.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>Add new item to your wardrobe</h3>
    <form action='' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock content %}

stylist/templates/stylist/login.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>Login</h3>
    <form action='' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <div class="large-4 columns">
                <input type="submit" value="Sign in">
            </div>
            <div class="large-8 columns text-right">
                If you don't have an account, <a href="{% url 'stylist:signup' %}">Sign up</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

stylist/templates/stylist/my_items.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>My wardrobe</h3>
    <ul>
        {% for item in object_list %}
        <li>{{ item }} - {{ item.description }}
            [<a href="{% url 'stylist:remove_item' item.pk %}">Remove</a>]
        </li>
        {% empty %}
            You have no clothes added yet.
        {% endfor %}
    </ul>
    <a href="{% url 'stylist:add_item' %}">Add item</a>
</div>
{% endblock content %}

stylist/templates/stylist/signup.html
{% extends "stylist/base.html" %}

{% block content %}
<div class="row medium-8 large-4 columns">
    <h3>Sign up</h3>
    <form id="signup" action='' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>
</div>
<script>
    $("#signup").submit(function(event) {
        getWoeid($('#id_zip_code').val());
        event.preventDefault();
    });
</script>

<script>
    function getWoeid(zip_code) {
        var YQL = "https://query.yahooapis.com/v1/public/yql";
        var url = YQL + "?q=select woeid from geo.places where text='" + zip_code + ",US" + "' and placeTypeName='Zip Code' limit 1;&format=json";
        // Test: url = "/static/test_signup.js";
        apiCall(url, callbackFunction)
    }

    var callbackFunction = function(data, retryFunc) {
        try {
            var results = data.query.results;
            if (results) {
                var woeid = results.place.woeid;
                if (woeid != undefined) {
                    $('#id_woeid').val(woeid);
                    $("#signup").off( "submit" ).submit();
                } else {
                    alert("Please correct Zip code and try again.");
                }
            } else {
                alert("Please correct Zip code and try again.");
            }
        } catch(e) {
            retryFunc("Problem communicating with the server. Try again later.");
        }
    };
</script>
{% endblock content %}

stylist/templates/stylist/what_to_wear.html
<p>Temperature: {{ low }} - {{ high }}</p>

{% if clothes %}
<ul>
    <li>
        Top: {{ clothes.0 }}
    </li>
    <li>
        Bottom: {{ clothes.1 }}
    </li>
    {% if sweater_needed %}
        <li>
            Other: {% if clothes.2 %}{{ clothes.2 }}{% else %}You should wear sweater today, but you don't have one.{% endif %}
        </li>
    {% endif %}
</ul>
{% else %}
    <p>You don't have suitable clothes for today, go shopping!</p>
{% endif %}